name: TinyNextSelect
author: danillos 
category: Forms
tags: [events, input, select]
docs: http://github.com/danillos/tiny-next-select/blob/master/Docs/TinyNextSelect.md
demo: http://www.danillocesar.com.br/labs/tiny-next-select
current: 0.2